// Java Package xault is a proxy for talking to a Go program.
//   gobind -lang=java github.com/runningwild/xault/shared/phone/xault
//
// File is generated by gobind. Do not edit.
package go.xault;

import go.Seq;

public abstract class Xault {
    private Xault() {} // uninstantiable
    
    public static void DestroyKeys() throws Exception {
        go.Seq _in = new go.Seq();
        go.Seq _out = new go.Seq();
        Seq.send(DESCRIPTOR, CALL_DestroyKeys, _in, _out);
        String _err = _out.readUTF16();
        if (_err != null) {
            throw new Exception(_err);
        }
    }
    
    public static final class LifetimeState implements go.Seq.Object {
        private static final String DESCRIPTOR = "go.xault.LifetimeState";
        private static final int CALL_DestroyKeys = 0x00c;
        private static final int CALL_LoadKeys = 0x10c;
        private static final int CALL_MakeKeys = 0x20c;
        private static final int CALL_SetRootDir = 0x30c;
        
        private go.Seq.Ref ref;
        
        private LifetimeState(go.Seq.Ref ref) { this.ref = ref; }
        
        public go.Seq.Ref ref() { return ref; }
        
        public void call(int code, go.Seq in, go.Seq out) {
            throw new RuntimeException("internal error: cycle: cannot call concrete proxy");
        }
        
        
        public void DestroyKeys() throws Exception {
            go.Seq _in = new go.Seq();
            go.Seq _out = new go.Seq();
            _in.writeRef(ref);
            Seq.send(DESCRIPTOR, CALL_DestroyKeys, _in, _out);
            String _err = _out.readUTF16();
            if (_err != null) {
                throw new Exception(_err);
            }
        }
        
        public void LoadKeys() throws Exception {
            go.Seq _in = new go.Seq();
            go.Seq _out = new go.Seq();
            _in.writeRef(ref);
            Seq.send(DESCRIPTOR, CALL_LoadKeys, _in, _out);
            String _err = _out.readUTF16();
            if (_err != null) {
                throw new Exception(_err);
            }
        }
        
        public void MakeKeys(String name) throws Exception {
            go.Seq _in = new go.Seq();
            go.Seq _out = new go.Seq();
            _in.writeRef(ref);
            _in.writeUTF16(name);
            Seq.send(DESCRIPTOR, CALL_MakeKeys, _in, _out);
            String _err = _out.readUTF16();
            if (_err != null) {
                throw new Exception(_err);
            }
        }
        
        public void SetRootDir(String path) throws Exception {
            go.Seq _in = new go.Seq();
            go.Seq _out = new go.Seq();
            _in.writeRef(ref);
            _in.writeUTF16(path);
            Seq.send(DESCRIPTOR, CALL_SetRootDir, _in, _out);
            String _err = _out.readUTF16();
            if (_err != null) {
                throw new Exception(_err);
            }
        }
        
        @Override public boolean equals(Object o) {
            if (o == null || !(o instanceof LifetimeState)) {
                return false;
            }
            LifetimeState that = (LifetimeState)o;
            return true;
        }
        
        @Override public int hashCode() {
            return java.util.Arrays.hashCode(new Object[] {});
        }
        
        @Override public String toString() {
            StringBuilder b = new StringBuilder();
            b.append("LifetimeState").append("{");
            return b.append("}").toString();
        }
        
    }
    
    public static void LoadKeys() throws Exception {
        go.Seq _in = new go.Seq();
        go.Seq _out = new go.Seq();
        Seq.send(DESCRIPTOR, CALL_LoadKeys, _in, _out);
        String _err = _out.readUTF16();
        if (_err != null) {
            throw new Exception(_err);
        }
    }
    
    public static void MakeKeys(String name) throws Exception {
        go.Seq _in = new go.Seq();
        go.Seq _out = new go.Seq();
        _in.writeUTF16(name);
        Seq.send(DESCRIPTOR, CALL_MakeKeys, _in, _out);
        String _err = _out.readUTF16();
        if (_err != null) {
            throw new Exception(_err);
        }
    }
    
    public static void SetRootDir(String path) throws Exception {
        go.Seq _in = new go.Seq();
        go.Seq _out = new go.Seq();
        _in.writeUTF16(path);
        Seq.send(DESCRIPTOR, CALL_SetRootDir, _in, _out);
        String _err = _out.readUTF16();
        if (_err != null) {
            throw new Exception(_err);
        }
    }
    
    private static final int CALL_DestroyKeys = 1;
    private static final int CALL_LoadKeys = 2;
    private static final int CALL_MakeKeys = 3;
    private static final int CALL_SetRootDir = 4;
    private static final String DESCRIPTOR = "xault";
}
